[tool.mypy]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "app.database.migrations.*"
ignore_errors = true

[tool.black]
line-length = 88
exclude = '''
  /(
    migrations
  )/
'''

[tool.isort]
profile = "black"
extend_skip = [
  'migrations'
]